import { prisma } from "@/lib/db";
import { getSession } from "@/lib/session";
import { PageHeader } from "@/components/ui";
import { addBookingPaymentAction, createBookingAction } from "@/lib/booking-credit-actions";
import { inr, num } from "@/lib/money";
import { connection } from "next/server";
import Link from "next/link";

export default async function BookingsPage() {
  await connection();
  const session = await getSession();
  const [bookings, customers] = await Promise.all([
    prisma.advanceBooking.findMany({ orderBy: { date: "desc" }, take: 200 }),
    prisma.customer.findMany({ orderBy: { name: "asc" }, select: { id: true, name: true, phone: true } }),
  ]);
  const totalAdvance = bookings.reduce((sum, row) => sum + num(row.advancePaid), 0);
  const outstanding = bookings.reduce((sum, row) => sum + num(row.balanceAmount), 0);
  return <div className="space-y-6"><PageHeader eyebrow="Customer commitments" title="Advance bookings" subtitle="Record made-to-order jewellery bookings, deposits, delivery dates, and the staff member who served the customer." />
    <div className="grid gap-3 sm:grid-cols-3">{[["Bookings", bookings.length], ["Advance collected", inr(totalAdvance)], ["Outstanding", inr(outstanding)]].map(([label, value]) => <div key={label} className="rounded-xl border border-sand bg-white p-4"><p className="text-xs text-stone">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>)}</div>
    <form action={createBookingAction} className="rounded-xl border border-sand bg-white p-5"><h2 className="mb-4 font-semibold">New booking</h2><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
      <label className="text-sm">Existing customer<select name="customerId" className="mt-1 w-full rounded border border-sand p-2"><option value="">Walk-in / enter below</option>{customers.map((customer) => <option key={customer.id} value={customer.id}>{customer.name} · {customer.phone}</option>)}</select></label><label className="text-sm">Customer name<input required name="customerName" className="mt-1 w-full rounded border border-sand p-2" /></label><label className="text-sm">Mobile<input name="customerPhone" className="mt-1 w-full rounded border border-sand p-2" /></label><label className="text-sm">Item description<input required name="description" className="mt-1 w-full rounded border border-sand p-2" /></label>
      <label className="text-sm">Product code<input name="productCode" className="mt-1 w-full rounded border border-sand p-2" /></label><label className="text-sm">Category<input name="category" className="mt-1 w-full rounded border border-sand p-2" /></label><label className="text-sm">Metal<select name="metal" className="mt-1 w-full rounded border border-sand p-2"><option>GOLD</option><option>SILVER</option><option>PLATINUM</option></select></label>
      <label className="text-sm">Approx. weight (g)<input name="approximateWeight" type="number" min="0" step="0.001" className="mt-1 w-full rounded border border-sand p-2" /></label><label className="text-sm">Purity<input name="purity" placeholder="22K" className="mt-1 w-full rounded border border-sand p-2" /></label><label className="text-sm">Gold rate / g<input name="goldRate" type="number" min="0" step="0.01" className="mt-1 w-full rounded border border-sand p-2" /></label>
      <label className="text-sm">Booking amount<input required name="bookingAmount" type="number" min="0.01" step="0.01" className="mt-1 w-full rounded border border-sand p-2" /></label><label className="text-sm">Advance paid<input required name="advancePaid" type="number" min="0" step="0.01" defaultValue="0" className="mt-1 w-full rounded border border-sand p-2" /></label><label className="text-sm">Payment mode<select name="paymentMode" className="mt-1 w-full rounded border border-sand p-2">{["CASH", "UPI", "CARD", "CHEQUE", "BANK"].map((mode) => <option key={mode}>{mode}</option>)}</select></label>
      <label className="text-sm">Expected delivery<input name="expectedDelivery" type="date" className="mt-1 w-full rounded border border-sand p-2" /></label><label className="text-sm">Making charges<input name="makingCharges" type="number" min="0" step="0.01" className="mt-1 w-full rounded border border-sand p-2" /></label><label className="text-sm">Tax / GST<input name="taxAmount" type="number" min="0" step="0.01" className="mt-1 w-full rounded border border-sand p-2" /></label>
      <label className="text-sm sm:col-span-2 lg:col-span-3">Special instructions<textarea name="instructions" rows={2} className="mt-1 w-full rounded border border-sand p-2" /></label>
    </div><button className="mt-4 rounded bg-royal-deep px-4 py-2 text-sm font-semibold text-white">Save booking</button><p className="mt-2 text-xs text-stone">Created by {session?.employeeName ?? session?.username} · {session?.employeeCode ?? ""}</p></form>
    <section className="rounded-xl border border-sand bg-white p-5"><h2 className="mb-3 font-semibold">Booking register</h2><div className="overflow-x-auto"><table className="w-full min-w-[940px] text-left text-sm"><thead><tr className="border-b text-stone"><th className="p-2">Booking</th><th className="p-2">Customer</th><th className="p-2">Item</th><th className="p-2">Amount</th><th className="p-2">Advance</th><th className="p-2">Balance</th><th className="p-2">Delivery</th><th className="p-2">Status</th><th className="p-2">Biller</th><th className="p-2">Actions</th></tr></thead><tbody>{bookings.map((row) => <tr key={row.id} className="border-b border-sand/70"><td className="p-2 font-mono">{row.bookingNo}</td><td className="p-2">{row.customerName}<div className="text-xs text-stone">{row.customerPhone}</div></td><td className="p-2">{row.description}<div className="text-xs text-stone">{row.metal} · {row.purity}</div></td><td className="p-2">{inr(num(row.bookingAmount))}</td><td className="p-2">{inr(num(row.advancePaid))}</td><td className="p-2">{inr(num(row.balanceAmount))}</td><td className="p-2">{row.expectedDelivery?.toLocaleDateString("en-IN") ?? "—"}</td><td className="p-2">{row.status}</td><td className="p-2">{row.billerName}<div className="text-xs text-stone">{row.employeeCode} · {row.counterNumber}</div></td><td className="p-2"><Link className="font-semibold text-royal" href={`/bookings/${row.id}`}>Receipt</Link>{row.balanceAmount.toNumber() > 0 && <form action={addBookingPaymentAction} className="mt-1 space-y-1"><input type="hidden" name="id" value={row.id} /><input required name="amount" type="number" min="0.01" max={row.balanceAmount.toNumber()} step="0.01" placeholder="Amount" className="w-24 rounded border border-sand p-1 text-xs" /><select name="mode" className="rounded border border-sand p-1 text-xs">{["CASH", "UPI", "CARD", "CHEQUE", "BANK"].map((mode) => <option key={mode}>{mode}</option>)}</select><button className="block text-xs font-semibold text-royal">Record payment</button></form>}</td></tr>)}</tbody></table></div></section>
  </div>;
}
