import { prisma } from "@/lib/db";
import { getSession } from "@/lib/session";
import { PageHeader } from "@/components/ui";
import { adjustCreditNoteAction, approveCreditNoteAction, createCreditNoteAction, rejectCreditNoteAction } from "@/lib/booking-credit-actions";
import { inr, num } from "@/lib/money";
import { connection } from "next/server";

export default async function CreditNotesPage() {
  await connection();
  const session = await getSession();
  const [invoices, notes] = await Promise.all([
    prisma.invoice.findMany({ where: { status: "FINAL" }, orderBy: { date: "desc" }, take: 300, select: { id: true, invoiceNo: true, customerName: true, date: true, grandTotal: true } }),
    prisma.creditNote.findMany({ include: { adjustments: { orderBy: { createdAt: "desc" } } }, orderBy: { createdAt: "desc" }, take: 200 }),
  ]);
  const outstanding = notes.reduce((sum, note) => sum + num(note.remainingBalance), 0);
  return <div className="space-y-6"><PageHeader eyebrow="Returns & exchange credit" title="Credit notes" subtitle="Create credit requests, record manager approval, and apply available credit to future invoices." />
    <div className="grid gap-3 sm:grid-cols-3">{[["Credit notes", notes.length], ["Awaiting approval", notes.filter((note) => note.status === "PENDING").length], ["Outstanding credit", inr(outstanding)]].map(([label, value]) => <div key={label} className="rounded-xl border border-sand bg-white p-4"><p className="text-xs text-stone">{label}</p><p className="mt-1 text-xl font-semibold">{value}</p></div>)}</div>
    <form action={createCreditNoteAction} className="rounded-xl border border-sand bg-white p-5"><h2 className="mb-4 font-semibold">Create credit note request</h2><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm sm:col-span-2">Original invoice<select required name="invoiceId" className="mt-1 w-full rounded border border-sand p-2"><option value="">Choose an invoice</option>{invoices.map((row) => <option key={row.id} value={row.id}>{row.invoiceNo} · {row.customerName} · {inr(num(row.grandTotal))}</option>)}</select></label><label className="text-sm">Credit amount<input required name="creditAmount" type="number" min="0.01" step="0.01" className="mt-1 w-full rounded border border-sand p-2" /></label><label className="text-sm">Reason<input required name="reason" className="mt-1 w-full rounded border border-sand p-2" /></label></div><button className="mt-4 rounded bg-royal-deep px-4 py-2 text-sm font-semibold text-white">Submit for approval</button></form>
    <section className="rounded-xl border border-sand bg-white p-5"><h2 className="mb-3 font-semibold">Credit note register</h2><div className="space-y-3">{notes.map((note) => <article key={note.id} className="rounded-lg border border-sand p-4"><div className="flex flex-wrap items-start justify-between gap-3"><div><strong>{note.creditNoteNo}</strong><span className="ml-2 rounded bg-sand/50 px-2 py-1 text-xs">{note.status}</span><p className="mt-1 text-sm">{note.customerName} · invoice {note.invoiceNo}</p><p className="text-xs text-stone">{note.reason} · Created by {note.createdByName} ({note.employeeCode})</p></div><div className="text-right text-sm"><p>Credit {inr(num(note.creditAmount))}</p><p className="font-semibold">Available {inr(num(note.remainingBalance))}</p>{note.approvedByName && <p className="text-xs text-stone">Approved by {note.approvedByName} · {note.approvedAt?.toLocaleString("en-IN")}</p>}</div></div>
        {note.status === "PENDING" && (session?.role === "admin" || session?.role === "manager") && <div className="mt-3 flex gap-2"><form action={approveCreditNoteAction}><input type="hidden" name="id" value={note.id} /><button className="rounded bg-emerald-700 px-3 py-1.5 text-xs font-semibold text-white">Approve</button></form><form action={rejectCreditNoteAction}><input type="hidden" name="id" value={note.id} /><button className="rounded border border-red-300 px-3 py-1.5 text-xs text-red-700">Reject</button></form></div>}
        {note.status === "APPROVED" && <form action={adjustCreditNoteAction} className="mt-3 flex flex-wrap items-end gap-2"><input type="hidden" name="id" value={note.id} /><label className="text-xs">Apply to invoice<select required name="invoiceId" className="mt-1 block rounded border border-sand p-2"><option value="">Select finalized bill</option>{invoices.map((invoice) => <option key={invoice.id} value={invoice.id}>{invoice.invoiceNo} · {invoice.customerName}</option>)}</select></label><label className="text-xs">Amount<input required name="amount" type="number" min="0.01" max={num(note.remainingBalance)} step="0.01" className="mt-1 block rounded border border-sand p-2" /></label><button className="rounded bg-royal-deep px-3 py-2 text-xs font-semibold text-white">Apply credit</button></form>}
        {note.adjustments.length > 0 && <details className="mt-3 text-xs"><summary className="cursor-pointer font-semibold">Adjustment history ({note.adjustments.length})</summary><ul className="mt-2 space-y-1">{note.adjustments.map((row) => <li key={row.id}>{inr(num(row.amount))} applied to {row.invoiceNo} · {row.createdAt.toLocaleString("en-IN")} · {row.employeeCode}</li>)}</ul></details>}
      </article>)}</div></section>
  </div>;
}
